# Generated by Django 5.0.4 on 2024-05-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
