# Generated by Django 5.0.4 on 2024-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_Bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
